name = "move-car-notify"
main = "src/index.js"
compatibility_date = "2024-04-30"

[vars]
PHONE_NUMBER = "18217840528"
BARK_URL = "https://bark.zznuo.com/SgjCabfe6UkXXcBSN4mogx/有人找你挪车啦/请尽快处理"
PUSHPLUS_TOKEN = "514ebbedcc914f4f94c01ffc0a30dcba"
